In [1]:
#Add two numbers and print the result
num1 = 3.2
nums2 = 4.5
result = num1 + nums2
print(result)

7.7


In [ ]:





#put from the user and add two numbers
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
result = num1 + num2
print("The sum of", num1, "and", num2, "is", result)




   

In [ ]:
#python proram to calculate square root of a number
import math
num = float(input("Enter a number: "))
sqrt = math.sqrt(num)
print("The square root of", num, "is", sqrt)

Enter a number:  4


The square root of 4.0 is 2.0


In [ ]:
#find square root of real or complex number
import cmath
num = complex(input("Enter a number: "))
sqrt = cmath.sqrt(num)
print("The square root of", num, "is", sqrt)


Enter a number:  5


The square root of (5+0j) is (2.23606797749979+0j)


In [ ]:
#Program to calculate frienhiet to celcius
fahrenheit = float(input("Enter temperature in Fahrenheit: "))
celsius = (fahrenheit - 32) * 5.0/9.0
print("The temperature in Celsius is:", celsius)


Enter temperature in Fahrenheit:  5


The temperature in Celsius is: -15.0


In [ ]:
#Area of triagnle
base = float(input("Enter the base of the triangle: ")) 
height = float(input("Enter the height of the triangle: "))
area = 0.5 * base * height
print("The area of the triangle is:", area)


Enter the base of the triangle:  4
Enter the height of the triangle:  6


The area of the triangle is: 12.0


In [ ]:
#Quadratic equation
import cmath
a = float(input("Enter the coefficient a: "))
b = float(input("Enter the coefficient b: "))
c = float(input("Enter the coefficient c: "))
d = (b**2) - (4*a*c)
sqrt_d = cmath.sqrt(d)
root1 = (-b + sqrt_d) / (2*a)
root2 = (-b - sqrt_d) / (2*a)
print("The roots are:", root1, "and", root2)


Enter the coefficient a:  6
Enter the coefficient b:  4
Enter the coefficient c:  3


The roots are: (-0.3333333333333333+0.6236095644623235j) and (-0.3333333333333333-0.6236095644623235j)


In [ ]:
#Taking KM from user and converting it to miles and factor
km = float(input("Enter distance in kilometers: "))
miles = km * 0.621371
factor = 0.621371
print("The distance in miles is:", miles)
print("The conversion factor is:", factor)

Enter distance in kilometers:  45


The distance in miles is: 27.961695
The conversion factor is: 0.621371


In [ ]:
#use if else to check greater number
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
if num1 > num2:
    print(num1, "is greater than", num2)
elif num2 > num1:
    print(num2, "is greater than", num1)
else:
    print("Both numbers are equal")
    

Enter the first number:  65
Enter the second number:  5


65.0 is greater than 5.0


In [ ]:
#use if else to check less number
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
if num1 < num2:
    print(num1, "is less than", num2)
elif num2 < num1:
    print(num2, "is less than", num1)
else:
    print("Both numbers are equal")

Enter the first number:  6
Enter the second number:  5


5.0 is less than 6.0


In [ ]:
#For loop
name = 'Abdullah'
for n in name:
    print(n)

A
b
d
u
l
l
a
h


In [ ]:
#for loop range
for i  in range (1,100):
    print(i ,end =" ")
    


1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 

In [ ]:
for i in range(1,20,3):
     print(i,end=" ")

1 4 7 10 13 16 19 

In [ ]:
# Prints all letters except 's' and 'i'
for st in "This is the python practice program and i am excited to do this task":
    if st == 's' or st == 'i':
       continue
    print(st,end = ' ')

T h     t h e   p y t h o n   p r a c t c e   p r o g r a m   a n d     a m   e x c t e d   t o   d o   t h   t a k 

In [ ]:
#use break
for st in "This is the python practice program and i am excited to do this task":
    if st == 'p':
      break
    print(st,end = ' ')

T h i s   i s   t h e   

In [ ]:
#use pass 
for st in "This is the python practice program and i am excited to do this task":
      pass
print(st,end = ' ')

k 

In [ ]:
#use enumurate
li = ['apple','grape','banana','orange']
for st,sk in enumerate(li):
    
    print(st,sk)

0 apple 1 grape 2 banana 3 orange 

In [ ]:
#nested loop
for i in range(1,4):
    for j in range(1,4):
        print(i,j,end = ' ')    


1 1 1 2 1 3 2 1 2 2 2 3 3 1 3 2 3 3 

In [ ]:
#While loop
i = 1
while i <= 5:
    print("Hello, World!",end = ' ')
    i += 1
    

In [ ]:
# Prints all letters except 'e' and 's' use continue key word
count = 0
string = "This is python course and there is perform python task"
while count < len(string):
    if string[count] == 's' or string[count]=='O':
        count +=  1
        continue 
    print(string[count])
    count += 1

In [ ]:
# Prints all letters except 'e' and 's' use pass key word
count = 0
string = "This is python course and there is perform python task"
while count < len(string):
    if string[count] == 's' or string[count] == 'e':
        count += 1
        pass
    print(string[count])
    count += 1

In [ ]:
#Break statement in while loop
count = 0
string = "This is python course and there is perform python task"
while count < len(string):
    if string[count] == 'p':
        break
    print(string[count],end = ' ')
    count += 1
    

T h i s   i s   

In [ ]:
#Python break statement
a=[1,2,3,4,5]
for i in a:
    if i==4:
        break
    print(i)
else:
    print("Loop is completed without break")

1
2
3


In [ ]:
#Python without break statement
a=[1,2,3,4,5]
for i in a:
    print(i)

1
2
3
4
5


In [ ]:
#Using break in Nested Loops  using 3D list
list_3d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
val = 5
found = False
for i in list_3d:
    for j in i:
        if j == val:
            print(f"{val} found in the list")
            found = True
            break
        print(j, end=' ')
if not found:
    print(f"{val} not found in the list")

1 2 3 4 5 found in the list
7 8 9 

In [18]:
#Exercise on various looping techniques in Python
#Using enumerate()
print("Using enumerate():")
fruits = ['apple', 'banana', 'cherry', 'date']
for index, fruit in enumerate(fruits):
    print(f"Index: {index}, Fruit: {fruit}")

#Using zip()
print("Using zip():")
colors = ['red', 'green', 'blue']
sizes = ['small', 'medium', 'large']
for color, size in zip(colors, sizes):
    print(f"Color: {color}, Size: {size}")

#Using items()
print("Using items():")
person = {'name': 'Alice', 'age': 30, 'city': 'New York'}
for key, value in person.items():
    print(f"{key}: {value}")    

#Using sorted()
print("Using sorted():")
numbers = [5, 2, 9, 1, 5, 6]
for num in sorted(numbers):
    print(num)

#Using reversed()
print("Using reversed():")
fruits = ['apple', 'banana', 'cherry', 'date']
for fruit in reversed(fruits):
    print(fruit)


#While Loop with If Condition
print("While Loop with If Condition:")
count = 0
while count < 10:
    if count == 5:
        print("count is 5, breaking the loop.")
       
    count += 1

Using enumerate():
Index: 0, Fruit: apple
Index: 1, Fruit: banana
Index: 2, Fruit: cherry
Index: 3, Fruit: date
Using zip():
Color: red, Size: small
Color: green, Size: medium
Color: blue, Size: large
Using items():
name: Alice
age: 30
city: New York
Using sorted():
1
2
5
5
6
9
Using reversed():
date
cherry
banana
apple
While Loop with If Condition:
count is 5, breaking the loop.


In [ ]:
#Defininng a function to calculate factorial of a number
print("Deffining Function")
def fun():
    print("Hello World")
fun()

print("Deffining Function with parameter")
def evenodd(x):
    if x % 2 == 0:
        print(x, "is an even number.")
    else:
        print(x, "is an odd number.")

evenodd(5)
evenodd(10)

#1. Default Arguments
print("Default Arguments:")
def greet(id=1,name="Guest"):
    print(f"Hello, {id}\ng{name} !",end = ' ')
greet()  # Uses default argument

#2. Keyword Arguments
print("Keyword Arguments:")
def greet(id,name):
    print(f"Hello, {id}\n{name} !",end = ' ')
greet( id=2,name="Alice")  # Using keyword arguments

#3. Variable-length Arguments
print("Variable-length Arguments:")         
def greet(*names):
    for name in names:
        print(f"Hello, {name}!",end = ' ')
greet("Alice", "Bob", "Charlie")  # Passing multiple arguments

#4. Arbitrary Arguments
print("Arbitrary Arguments:")         
def greet(**kwargs):
    for key, value in kwargs.items():
        print(f"Hello, {key}! You are {value}.")
greet(Alice="25", Bob="30", Charlie="35")  # Passing multiple keyword arguments

# Function within Functions
print("Function within Functions:")
def outer_function():
    print("This is the outer function.")
    
    def inner_function():
        print("This is the inner function.")
    
    inner_function()

outer_function()

Deffining Function
Hello World
Deffining Function with parameter
5 is an odd number.
10 is an even number.
Default Arguments:
Hello, 1
gGuest ! Keyword Arguments:
Hello, 2
Alice ! Variable-length Arguments:
Hello, Alice! Hello, Bob! Hello, Charlie! Arbitrary Arguments:
Hello, Alice! You are 25.
Hello, Bob! You are 30.
Hello, Charlie! You are 35.
Function within Functions:
This is the outer function.
This is the inner function.


In [ ]:
#List
my_list = [1, 2, 3, 4, 5]
print(my_list)

#List Items of Different Types
my_mixed_list = [1, "Hello", 3.14, True]
print(my_mixed_list)

#Access List Elements
languages = ['Python', 'Swift', 'C++']

# access the first element
print('languages[0] =', languages[0])

# access the third element
print('languages[2] =', languages[2])

#Negative Indexing
print('languages[-1] =', languages[-1])  # last element
print('languages[-2] =', languages[-2])  # second last element
print('languages[-3] =', languages[-3])  # third last element 

#Slicing of a List in Python
print('languages[0:2] =', languages[0:2])  # elements from index 0 to 1
print('languages[1:3] =', languages[1:3])  # elements from index 1 to 2
print('languages[:2] =', languages[:2])    # elements from start to index 1
print('languages[1:] =', languages[1:])    # elements from index 1 to end
print('languages[-2:] =', languages[-2:])  # last two elements

#Omitting Start and End Indices in Slicing
print('languages[:] =', languages[:])      # all elements   
print('languages[1:] =', languages[1:])    # elements from index 1 to end
print('languages[:2] =', languages[:2])    # elements from start to index 1
print('languages[-2:] =', languages[-2:])  # last two elements      

#Add Elements to a Python List
my_list = [1, 2, 3]
my_list.append(4)  # Adds 4 to the end of the list  
print(my_list)

#Add Elements at the Specified Index
my_list = [1, 2, 3]
my_list.insert(1, 10)  # Inserts 10 at index 1  
print(my_list)

#Add Elements to a List From Other Iterables
my_list = [1, 2, 3]
my_list.extend([4, 5, 6])  # Extends the list with another list
print(my_list)  

#Change List Items
my_list = [1, 2, 3]
my_list[0] = 10  # Changes the first element to 10
print(my_list)

#REMOVE ELEMENTS FROM A LIST
my_list = [1, 2, 3, 4, 5]       
my_list.remove(3)  # Removes the element 3 from the list
print(my_list)  

#Remove an Element at a Specified Index
my_list = [1, 2, 3, 4, 5]   
my_list.pop(2)  # Removes the element at index 2
print(my_list)  

[1, 2, 3, 4, 5]
[1, 'Hello', 3.14, True]
languages[0] = Python
languages[2] = C++
languages[-1] = C++
languages[-2] = Swift
languages[-3] = Python
languages[0:2] = ['Python', 'Swift']
languages[1:3] = ['Swift', 'C++']
languages[:2] = ['Python', 'Swift']
languages[1:] = ['Swift', 'C++']
languages[-2:] = ['Swift', 'C++']
languages[:] = ['Python', 'Swift', 'C++']
languages[1:] = ['Swift', 'C++']
languages[:2] = ['Python', 'Swift']
languages[-2:] = ['Swift', 'C++']
[1, 2, 3, 4]
[1, 10, 2, 3]
[1, 2, 3, 4, 5, 6]
[10, 2, 3]
[1, 2, 4, 5]
[1, 2, 4, 5]


In [ ]:
#tuple
my_tuple = (1, 2, 3, 4, 5)
print(my_tuple) 


#Access Items Using Index
print('my_tuple[0] =', my_tuple[0])     
print('my_tuple[2] =', my_tuple[2])     
print('my_tuple[-1] =', my_tuple[-1])    # last element
print('my_tuple[-2] =', my_tuple[-2])    # second last element




#tuple modified by converting it to a list
cars = ('BMW', 'Tesla', 'Ford', 'Toyota')
cars_list = list(cars)  # Convert tuple to list
cars_list[0] = 'Nissan'  # Modify the list
cars = tuple(cars_list)  # Convert back to tuple
print(cars)  # Output: ('Nissan', 'Tesla', 'Ford', 'Toyota')  

#tuple cannot be modified
cars = ('BMW', 'Tesla', 'Ford', 'Toyota')

# trying to modify a tuple
cars[0] = 'Nissan'    # error
       
print(cars)



(1, 2, 3, 4, 5)
my_tuple[0] = 1
my_tuple[2] = 3
my_tuple[-1] = 5
my_tuple[-2] = 4
('Nissan', 'Tesla', 'Ford', 'Toyota')


In [ ]:
#Create a Set in Python
my_set = {1, 2, 3, 4, 5}
print(my_set)
#Set with Mixed Data Types
my_mixed_set = {1, "Hello", 3.14, True}
print(my_mixed_set)

#Duplicate Items in a Set
my_duplicate_set = {1, 2, 2, 3, 3, 4, 4, 5, 5}
print(my_duplicate_set)  # Output: {1, 2, 3, 4, 5}

#Add Items to a Set in Python
my_set.add(6)
print(my_set)  # Output: {1, 2, 3, 4, 5, 6}
my_set.update([7, 8, 9])
print(my_set)  # Output: {1, 2, 3, 4, 5, 6, 7, 8, 9}

#Update Python Set
my_set.update([10, 11, 12])
print(my_set)  # Output: {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}

#Remove an Element from a Set
my_set.remove(1)  # Removes 1 from the set
print(my_set)  # Output: {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}
my_set.discard(2)  # Discards 2 from the setghji
#Union of Two Sets
set1 = {1, 2, 3}
set2 = {3, 4, 5}        
union_set = set1.union(set2)  # Union of set1 and set2
print(union_set)  # Output: {1, 2, 3,   4, 5}   

#Intersection of Two Sets
intersection_set = set1.intersection(set2)  # Intersection of set1 and set2
print(intersection_set)  # Output: {3}

#Difference of Two Sets
difference_set = set1.difference(set2)  # Difference of set1 and set2
print(difference_set)  # Output: {1, 2}

#Symmetric Difference of Two Sets
sym_diff_set = set1.symmetric_difference(set2)  # Symmetric difference of set1 and set2
print(sym_diff_set)  # Output: {1, 2, 4,    5}

#check two sets are equal or not
set1 = {1, 2, 3}
set2 = {3, 2, 1}
print(set1 == set2)  # Output: True



{1, 2, 3, 4, 5}
{1, 3.14, 'Hello'}
{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4, 5, 6, 7, 8, 9}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}
{2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}
{1, 2, 3, 4, 5}
{3}
{1, 2}
{1, 2, 4, 5}
True


In [ ]:
#Dectionary
my_dict = {'name': 'Alice', 'age': 30, 'city': 'New York'}
print(my_dict)

#Access Dictionary Items
print(my_dict['name'])  # Output: Alice
print(my_dict['age'])   # Output: 30
print(my_dict['city'])  # Output: New York

#Add Items to a Dictionary
my_dict['email'] = 'alice@example.com'
print(my_dict)  # Output: {'name': 'Alice', 'age': 30, 'city': 'New York', 'email': 'alice@example.com'}

#Remove Dictionary Items
del my_dict['age']  # Removes the key 'age' and its value
print(my_dict)  # Output: {'name': 'Alice', 'city': 'New York', 'email': 'alice@example.com'}

#Change Dictionary Items
my_dict['city'] = 'Los Angeles'  # Changes the value of 'city' to 'Los Angeles'
print(my_dict)  # Output: {'name': 'Alice', 'city': 'Los Angeles', 'email': 'alice@example.com'}

#Iterate Through a Dictionary
for key, value in my_dict.items():
    print(f"{key}: {value}")
    

{'name': 'Alice', 'age': 30, 'city': 'New York'}
Alice
30
New York
{'name': 'Alice', 'age': 30, 'city': 'New York', 'email': 'alice@example.com'}
{'name': 'Alice', 'city': 'New York', 'email': 'alice@example.com'}
{'name': 'Alice', 'city': 'Los Angeles', 'email': 'alice@example.com'}
name: Alice
city: Los Angeles
email: alice@example.com


In [3]:
#Exception Handling
try:
    num1 = int(input("Enter the first number: "))
    num2 = int(input("Enter the second number: "))
    result = num1 / num2
    print("The result of division is:", result)
except ZeroDivisionError:
    print("Error: Cannot divide by zero.")
except ValueError:
    print("Error: Invalid input. Please enter a valid number.")
    

Error: Invalid input. Please enter a valid number.


***NUMPY** and its uses.

In [ ]:
#numpy creation(List)
import numpy as np
arr =np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#numpy creation(tuple)
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)  


[1 2 3 4 5]


In [6]:
#numpy creation(dictionary)
import numpy as np
arr = np.array({'a': 1, 'b': 2, 'c': 3})
print(arr)


{'a': 1, 'b': 2, 'c': 3}


******Dimensions in Arrays***

In [15]:
#0 dimensional array   
print("0 Dimensional Array:") 
arr = np.array(42)
print(arr)
print(arr.ndim)

print("1 Dimensional Array:")
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(arr1.ndim)

print("2 Dimensional Array:")
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2)
print(arr2.ndim)

print("3 Dimensional Array:")
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3)

0 Dimensional Array:
42
0
1 Dimensional Array:
[1 2 3 4 5]
1
2 Dimensional Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
3 Dimensional Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [18]:
#Access element from array
print("Accessing Elements from 1D Array:")
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])  # Output: 1

print("Accessing Elements from 2D Array:")
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2[0][0])  # Output: 1
print(arr2[1][2])  # Output: 6

print("Accessing Elements from 3D Array:")
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3[0][0][0])  # Output: 1   
print(arr3[1][1][2])  # Output: 12

print("Negative Indexing in 1D Array:")
arr = np.array([1, 2, 3, 4, 5])
print(arr[-1])  # Output: 5
print(arr[-2])  # Output: 4
print("Negative Indexing in 2D Array:")
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2[-1][-1])  # Output: 9
print(arr2[-2][-2])  # Output: 5

Accessing Elements from 1D Array:
1
Accessing Elements from 2D Array:
1
6
Accessing Elements from 3D Array:
1
12
Negative Indexing in 1D Array:
5
4
Negative Indexing in 2D Array:
9
5


In [ ]:
#Numpy Slicing
print("Slicing 1D Array:")
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])  # Output: [2 3 4]
print(arr[:3])   # Output: [1 2 3]
print(arr[2:6])  # Output: [3 4 5]

print("Slicing 2D Array:")
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2[0:2, 0:2])  # Output: [[1# 2]# [4 5]]
print(arr2[:2, :2])    # Output: [[1 2]# [4 5]]
print(arr2[1:, 1:])    # Output: [[5 6]# [8 9]]

print("Slicing 3D Array:")
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3[0:2, 0:2, 0:2])
# Output: [[[ 1  2]
#  [ 4  5]]
# [[ 7  8]
#  [10 11]]]
print(arr3[:2, :2, :2])
# Output: [[[ 1  2]
#  [ 4  5]]
# [[ 7  8]

#  [10 11]]]
print(arr3[1:, 1:, 1:])
# Output: [[[ 5  6]
#  [10 11]]]


Slicing 1D Array:
[2 3 4]
[1 2 3]
[3 4 5]
Slicing 2D Array:
[[1 2]
 [4 5]]
[[1 2]
 [4 5]]
[[5 6]
 [8 9]]
Slicing 3D Array:
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]
[[[11 12]]]


In [21]:
#USING STEP IN SLICING
print("Using Step in Slicing 1D Array:")
arr = np.array([1, 2, 3, 4, 5])
print(arr[0:5:2])  # Output: [1 3 5
print("Using Step in Slicing 2D Array:")
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2[0:3:2, 0:3:2])  # Output: [[1 3]# [7 9]]


Using Step in Slicing 1D Array:
[1 3 5]
Using Step in Slicing 2D Array:
[[1 3]
 [7 9]]


**Numpy Data Types**

In [ ]:
#Numpy Interger Array
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.dtype)  # Output: int64 (or int32 depending on the system)

print("Numpy Float Array:")
arr_float = np.array([1.0, 2.0, 3.0])
arr_float = arr_float.astype('i')  # Convert to float if not already
print(arr_float)
print(arr_float.dtype)  # Output: float64

print("Numpy Complex Array:")
arr_complex = np.array([1 + 2j, 3 + 4j])
print(arr_complex)
print(arr_complex.dtype)  # Output: complex128

print("Numpy Boolean Array:")
arr_bool = np.array([1, 0, 1, 8], dtype=bool)
print(arr_bool)
print(arr_bool.dtype)  # Output: bool

print("Numpy String Array:")
arr_str = np.array(['apple', 'banana', 'cherry'])
print(arr_str)
print(arr_str.dtype)  # Output: <U7 (or similar)    

[1 2 3 4 5]
int64
Numpy Float Array:
[1 2 3]
int32
Numpy Complex Array:
[1.+2.j 3.+4.j]
complex128
Numpy Boolean Array:
[ True False  True  True]
bool
Numpy String Array:
['apple' 'banana' 'cherry' '8']
['apple' 'banana' 'cherry' '8']
<U21


In [5]:
#NumPy Array Copy vs View
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr_copy = arr.copy()  # Creates a copy of the array
arr_view = arr.view()  # Creates a view of the array
arr[0] = 10  # Modifying the original array 
print("Original Array:", arr)
print("Copy of the Array:", arr_copy)
print("View of the Array:", arr_view)

#NumPy Array Reshaping
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6,7,8,9,10,11,12])
reshaped_arr = arr.reshape(4, 3)  # Reshapes the array to 3 rows and 2 columns
print(reshaped_arr)

#NumPy Array Transpose
import numpy as np  
arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr = arr.T  # Transposes
print(transposed_arr)

#check the shape of numpy
arr = np.array([[1,43,54,5],[32,54,65,7],[45,4,2,65],[574,54,64,6]])
print(arr.shape)


Original Array: [10  2  3  4  5]
Copy of the Array: [1 2 3 4 5]
View of the Array: [10  2  3  4  5]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 4]
 [2 5]
 [3 6]]
(4, 4)


In [ ]:
#Numpy array iterating
import numpy as np
arr = np.array([21,23,43,5,34,53])

for i in arr:
    print(i)

#using if statement in there 
arr = np.array([7,45,64,65,767,868,97,856,3,5,])
for w in arr:
    if w == 97 or w == 5:
        print("these two number is required ")
        
    else:
        print("number iterating without any obstale")

#Numpy 2D array iterating 
arr = np.array([[1,2,3,4,64,5],[76,45,35,64,3,6]]) 
for u in arr:
    for t in u:
     print(t)




21
23
43
5
34
53
number iterating without any obstale
number iterating without any obstale
number iterating without any obstale
number iterating without any obstale
number iterating without any obstale
number iterating without any obstale
these two number is required 
number iterating without any obstale
number iterating without any obstale
these two number is required 
1
2
3
4
64
5
76
45
35
64
3
6
[3 2 1]
[ 6 34  5]
[4 4 6]


In [26]:
#Numpy 3D  array iterating
import numpy as np
arr =  np.array([[[3,2,1],[6,34,5],[4,4,6]]])
for h in arr:
  for y in h:
    for r in y:
      print(r)

3
2
1
6
34
5
4
4
6


In [28]:
#use nditer 
arr = np.array([[[1,4,2,5],[8,6,7,9],[7,8,4,6],[17,3,42,5]]])
for j in np.nditer(arr):
    print(j)

1
4
2
5
8
6
7
9
7
8
4
6
17
3
42
5


In [30]:
#Enumerated Iteration Using ndenumerate()
arr = np.array([[[[16,5,3,5,5],[8,6,5,7,54],[5,75,67,86,56]]]])
for index,t in np.ndenumerate(arr):
    print(index,t)


(0, 0, 0, 0) 16
(0, 0, 0, 1) 5
(0, 0, 0, 2) 3
(0, 0, 0, 3) 5
(0, 0, 0, 4) 5
(0, 0, 1, 0) 8
(0, 0, 1, 1) 6
(0, 0, 1, 2) 5
(0, 0, 1, 3) 7
(0, 0, 1, 4) 54
(0, 0, 2, 0) 5
(0, 0, 2, 1) 75
(0, 0, 2, 2) 67
(0, 0, 2, 3) 86
(0, 0, 2, 4) 56


In [39]:
#joining the arr in numpy
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,10,11,12])
arr3 = np.array([13,14,15])
concetinate_array = np.concatenate((arr1,arr2,arr3))
print(concetinate_array)

# joining 2D array in numpy
arr1 = np.array([[3,2,4,5],[9,5,3,7]])
arr2 = np.array([[17,14,5,2],[75,45,64,5]])
concetinate_array = np.concatenate((arr1,arr2),axis=1)
print(concetinate_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 3  2  4  5 17 14  5  2]
 [ 9  5  3  7 75 45 64  5]]


In [43]:
#using hstack,vstack,and dstack
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,10,11,12])

concetinate_array = np.vstack((arr1,arr2))
print(concetinate_array)

concetinate_array = np.hstack((arr1,arr2))
print(concetinate_array)

concetinate_array = np.dstack((arr1,arr2))
print(concetinate_array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  7]
  [ 2  8]
  [ 3  9]
  [ 4 10]
  [ 5 11]
  [ 6 12]]]


In [46]:
#Spiliting Array
arr = np.array([5,3,4,2,51,5,3,6,7,5])
split_arr = np.array_split(arr,4)

print(split_arr[0])
print(split_arr[1])
print(split_arr[2])
print(split_arr[3])

[5 3 4]
[ 2 51  5]
[3 6]
[7 5]


In [50]:
#Spliting 2D array in numpy
arr = np.array([[43,45,46,75,76],[90,43,64,67,54]])
split_arr = np.array_split(arr,4)
print(split_arr)


[array([[43, 45, 46, 75, 76]]), array([[90, 43, 64, 67, 54]]), array([], shape=(0, 5), dtype=int64), array([], shape=(0, 5), dtype=int64)]


In [52]:
#Array element searching by index
arr = np.array([4,5,3,53,4,3,5,3,5,3,6,7,8,54,6,4,3,6,3,6,7])
search_arr = np.where(arr==3)
print(search_arr)

(array([ 2,  5,  7,  9, 16, 18]),)


In [56]:
#find the even element
arr = np.array([4,5,3,53,4,3,5,3,5,3,6,7,8,54,6,4,3,6,3,6,7])
search_arr = np.where(arr%2==0)
print("Even Number indexes",search_arr)

Even Number indexes (array([ 0,  4, 10, 12, 13, 14, 15, 17, 19]),)


In [62]:
arr = np.array([2,3,4,5,7,9])
search_arr = np.searchsorted(arr,[1,6,8])
print(search_arr)



[0 4 5]


In [ ]:
#Sorted array in numpy
arr = np.array([4,5,3,53,4,3,5,3,5,3,6,7,8,54,6,4,3,6,3,6,7])
print(np.sort(arr))

# sort by alphabatical
arr = np.array(['Imran','Riaz','Huma','Laiba','Atiqa','Mushraf'])
print(np.sort(arr))

# Sort technique for 2D array
arr = np.array([[43,45,46,75,76],[90,43,64,67,54]])
print(np.sort(arr))




[ 3  3  3  3  3  3  4  4  4  5  5  5  6  6  6  6  7  7  8 53 54]
['Atiqa' 'Huma' 'Imran' 'Laiba' 'Mushraf' 'Riaz']
[[43 45 46 75 76]
 [43 54 64 67 90]]


In [ ]:
#Filter in Numpy
arr = np.array([43,42,56,78,56,58,87,67,53])
filter_arr = []

for i in arr:
    if i > 50:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
print(filter_arr)
newarr = arr[filter_arr]
print(newarr)
    
#Filter Even no
arr = np.array([43,42,56,78,56,58,87,67,53])
filter_arr = []

for i in arr:
    if i%2==0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
print(filter_arr)
newarr = arr[filter_arr]
print(newarr)
    


[False, False, True, True, True, True, True, True, True]
[56 78 56 58 87 67 53]
[False, True, True, True, True, True, False, False, False]
[42 56 78 56 58]
